<h1><?= $this->title ?></h1>

<a rel="nofollow" href="http://www.jacarandafm.co.za/demostation" title="Jacaranda's Demo Station">
	<img src="<?= $this->baseUrl() . '/img/demostation.jpg' ?>" alt="Jacaranda's Demo Station" width="560" />
	<h2>Jacaranda's Demo Station</h2>
</a>
<div id="ticketBox">
	<a rel="nofollow" href="http://www.computicket.com/web/event/demo_station_concert/3634100" title="Buy a Ticket at CompuTicket" target="_blank">
	<h5>Click here to buy a ticket</h5>
	<img src="<?= $this->baseUrl() . '/img/computicket.gif' ?>" alt="Buy a Ticket at CompuTicket" width="220" />
	</a>
</div>
<h3>11 July 2009</h3>
<p>Firstly, we would like to thank everyone that supported and voted for us! Aviya is in the quarter-finals for Jacaranda's Demo Station's competition.<br />
Aviya will be up against Klankgrenz to make it through to the semi-finals. Both the bands will be performing 2 songs &mdash; followed by Kurt Darren as the main performance.</p>
<p><a href="<?= $this->url(array('controller'=>'contact', 'action'=>'us'), 'default', true) ?>" title="Contact us">Contact us</a> if you would like more information.</p>

<h4 class="vvspace">Location: Silverstar Casino Centre</h4>
<p>Streetmaps</p>
<iframe width=500 height=500 src='http://www.streetmaps.co.za/map_iframe.asp?x=27.827560000000005&y=-26.06725000000002&z=0.005&sp=27.82789333333334|-26.06595000000002|Silverstar Casino' id='map_frame' scrolling=no style='border:none;' frameborder=no></iframe>

