-- phpMyAdmin SQL Dump
-- version 2.11.6
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generation Time: Jul 07, 2009 at 12:27 AM
-- Server version: 5.0.51
-- PHP Version: 5.2.6

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `aviya`
--

-- --------------------------------------------------------

--
-- Table structure for table `avi_albums`
--

DROP TABLE IF EXISTS `avi_albums`;
CREATE TABLE `avi_albums` (
  `id` int(11) NOT NULL auto_increment,
  `date_created` timestamp NOT NULL default CURRENT_TIMESTAMP,
  `date_modified` varchar(255) NOT NULL,
  `title` varchar(255) NOT NULL,
  `description` text NOT NULL,
  `cover` varchar(255) NOT NULL,
  PRIMARY KEY  (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=2 ;

--
-- Dumping data for table `avi_albums`
--

REPLACE INTO `avi_albums` (`id`, `date_created`, `date_modified`, `title`, `description`, `cover`) VALUES
(1, '2009-07-06 18:55:01', '1246907730', 'Flight of Time', 'After more than seven years of song writing the pieces of the puzzle finally started to fall into place... and two years later we have something to show for it. A fresh brand new CD with songs that kick uhm... you know what, and conveys powerful messages. Its all about the average person on the street and how we can relate to each other through common issues we face as humans. Take for instance the concept of time and how we never seem to have enough of it. Truly time fies like a frightened bird but we leave footprints behind in the sands of time.\r\n\r\nThe album wishes to capture some of these life experiences and lessons like a snapshot. We all face different seasons in our lives and as the songs were written over a long period of time it reflects different spheres of existence for instance from heartache to happiness it strives to be heartfelt and sincere. For this reason every song is unique with its own style and approach catering for people with different tastes and preferences. Therefore no matter who you are or what your background may be, i believe the Album caters for everybody and that in some strange way we are all able to relate.\r\n\r\nIronically while making this Album it was never a race against time! We truly took our time during the production putting as much care into every detail possible. The Album was recorded at Time line studios and produced by Dawid Jooste and Bruce Wallace. Now these guys are serious fun and really good at what they do. We had such a blast in the studio! Yes, yes in a way of speaking but also literally. I was privileged to work with a bunch of artists that are so talented and real with names like Mauritz Lotz, Johan Rautenbach, Denny Lalouette, Evert van Niekerk, Derrick Ruthven, Bruce Wallace and Dawid Jooste all well known artists in the Industry. Therefore i believe the result is the effort of collective genius.\r\n\r\nIt has been truely amaizing to see how the right people at the right time just crossed my path. Fate, destiny or the hand of God? I beleive the latter. The reality is that we all have something to say, and we all have been given ways to do so. Therefore i cannot emphasize this enough. This Album was written for your pleasure and enjoyment. Deep, alluring, at times a bit mysterious, it still conveys the truth about ourselves and society that we simply cannot deny.', 'Flight of Time_1246902982.jpg');

-- --------------------------------------------------------

--
-- Table structure for table `avi_tracks`
--

DROP TABLE IF EXISTS `avi_tracks`;
CREATE TABLE `avi_tracks` (
  `id` int(11) NOT NULL auto_increment,
  `date_created` timestamp NOT NULL default CURRENT_TIMESTAMP,
  `date_modified` varchar(255) NOT NULL,
  `albumID` int(11) NOT NULL,
  `trackNumber` int(11) NOT NULL,
  `trackTitle` varchar(255) NOT NULL,
  `trackLyrics` text NOT NULL,
  PRIMARY KEY  (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=13 ;

--
-- Dumping data for table `avi_tracks`
--

REPLACE INTO `avi_tracks` (`id`, `date_created`, `date_modified`, `albumID`, `trackNumber`, `trackTitle`, `trackLyrics`) VALUES
(1, '2009-07-06 20:39:29', '1246905569', 1, 1, 'So Sorry', 'There''s a girl posing in a photo shoot\r\nSometimes dressed, sometimes quite nude\r\nShe sells through her smile\r\nBut if you choose to take a while\r\nYou can see that there''s sadness in her eyes\r\n \r\nThey say\r\nSmile, like you mean it\r\nWhy don''t you smile like you care\r\n \r\nSo sorry I couldn''t make you stay\r\nSo sorry I couldn''t have my way\r\nSo sorry I couldn''t keep you mine\r\nCoz the seasons gone and we''ve run out of time\r\nIf I could, then I would\r\nFinally understand \r\nSomeday, someway\r\nI will find me peace\r\nBut till then I''ll be on my knees\r\n \r\nSo sorry I didn''t let you go\r\nSo sorry how was I supposed to know\r\nSo sorry I couldn''t change your mind\r\nNow we are all done and you''ve left me behind\r\nSo sorry I didn''t make you stay\r\nSo sorry I couldn''t have my way\r\nSo sorry I couldn''t keep you mine\r\nCoz the seasons gone and we''ve run out of time\r\n \r\nIf you ever love somebody\r\nLet it show\r\nOtherwise you might inspire them\r\nTo go'),
(2, '2009-07-06 20:48:22', '1246906102', 1, 2, 'Smile', 'The other day I was walking about\r\nA man came by, above his head a cloud\r\nI aked: "Sir, how do you do?"\r\nHe said: "Good and how are you?"\r\nGave me a quick glance then back at his shoe\r\nHis smile not worth a lot at all\r\n \r\nSmile, like you mean it\r\nWhy don''t you smile like you care\r\n \r\nThere''s a girl posing in a photo shoot\r\nSometimes dressed, sometimes quite nude\r\nShe sells through her smile\r\nBut if you choose to take a while\r\nYou can see that there''s sadness in her eyes\r\n \r\nThey say\r\nSmile, like you mean it\r\nWhy don''t you smile like you care\r\nThere''s a lady posing in a golden frame\r\nAll dressed up hands folded ready for fame\r\nHiding behind a mask that all is well\r\nBut if you look closer anyone can tell\r\nMona Lia''s smile is not all what it seem\r\n \r\nCan you\r\nSmile, like you mean it\r\nWhy don''t you smile like you care\r\n \r\nThe other day I was running around\r\nPassed the mirror on the way out\r\nCaught a glimpse of a face in the reflection\r\nI said: "Wait a minute what do I see?"\r\nCould that be really me?\r\nAnd tried to force a smile at last\r\n \r\nCome on now\r\nSmile, like you mean it\r\nWhy don''t you smile if you dare'),
(3, '2009-07-06 20:49:01', '1246906141', 1, 3, 'Slow Down', 'You better slow down baby\r\nYou got to take some time out and stop\r\nYou better slow down baby\r\nKeep going on like this and you are gonna drop\r\n \r\nThe world is filled with\r\nToo many people just trying to survive\r\nIn this rat race called life\r\n \r\nDon''t you dare join them\r\nThere''s too many things more important than that\r\nBut so then dare to ask yourself\r\nWhat do you do?\r\nWhen you''ve chased the power,\r\nthe money and the look\r\nWhere do you go from here?\r\nTo find directions in a map or a book\r\n \r\nSitting in the mall and\r\nWatching the people passing by\r\nSo caught up in their own little world\r\n \r\nBut life moves fast now\r\nYou have to hold on with all you''ve got\r\nAnd squeece some time in to live\r\n \r\nWhat do you do?\r\nWhen you''ve chased the power,\r\nthe money and the look\r\nWhere do you go from here?\r\nWhen you''ve sacrificed the things \r\nthat you hold dear?'),
(4, '2009-07-06 20:49:42', '1246906182', 1, 4, 'Resignation (Giving Up)', 'Giving up\r\nGiving in\r\nLetting go\r\n \r\nIt''s a resignation\r\nOut of desperation\r\nWhat a situation\r\nI rest my case\r\n \r\nI want to know why\r\nYou didn''t even try\r\nYou just let me go\r\nAnd now I know\r\n \r\nYou are:\r\nGiving up\r\nGiving in\r\nLetting go\r\nYou demand surrender\r\nBut I am a love defender\r\nNot like you a pretender\r\nBut I can''t fight this\r\n \r\nIf it''s meant to be\r\nExpect difficulty\r\nIf you''re not willing to fight for me\r\nWhat are you doing here?\r\n \r\nSo I am\r\nGiving up\r\nGiving in\r\nLetting go\r\n \r\nGiving up\r\nGiving in\r\nLetting go'),
(5, '2009-07-06 20:49:48', '1246906188', 1, 5, 'Through', 'You move through me like a hurricane\r\nYou call me names even say I am insane\r\nYou pick me up and then you bring me down\r\nI''ll be the joke and you''ll be the clown\r\n \r\nBecause\r\n \r\nI am through\r\nThrough with you\r\nTell me baby what am I supposed to do?\r\n \r\nYou move through me like a steaming train\r\nBurrowing tunnels right through my brain\r\nI am going to leave soon on a plane\r\nWon''t be back till I am sane!\r\n \r\nI am through\r\nThrough with you\r\nTell me baby what am I supposed to do?\r\nI am your light and you are my might\r\nI am your weakness, and you are my might\r\nI am your sunshine, you are my rain\r\nI am your pleasure and you are my pain\r\n \r\nI see through you like clear sky\r\nEvery beginning a sequel like you and I\r\nBook of events always halfway through\r\nHow do I get this through to you?\r\n \r\nI am through\r\nThrough with you\r\nTell me baby what am I supposed to do?'),
(6, '2009-07-06 20:50:29', '1246906229', 1, 6, 'Badly Misunderstood', 'After dinner she slips away\r\nTired of control and doing things their way\r\nShe finds a way to release and control\r\nTo compensate for the hole in her soul\r\n \r\nShe leaves the restroom hungry again\r\nHoping to escape the predicament she''s in\r\nDeep within lies a scared little girl\r\nAnd in this downward spiral she swirls\r\n \r\nShe is badly misunderstood\r\nTired of hearing what she aught to be or should\r\nAngry at those that pretend they know\r\nThe way she thinks and feels\r\nUnaware her unhappiness is so real\r\n \r\nHe''s all dressed in black\r\nWith earring and chains\r\nand hair that makes a statement\r\nHe says he doesn''t care\r\nAnd so does the slogan on his favourite t-shirt\r\nWhy do they call me a freak if I fit in?\r\nIf they knew the reasons\r\ndo you think they''d care?\r\nI am screaming through\r\nmy appearance cause they don''t\r\nWant to hear what I have to say\r\n \r\nHe is badly misunderstood\r\nTired of hearing what he aught to do or should\r\nAngry at those that pretend they know\r\nWhat he thinks and feels\r\nUnaware his unhappiness is so real\r\n \r\nShe shuts the door to keep the world outside\r\nIn fear that they will see the hurt inside\r\nShe already feels too exposed and alone\r\nShe dare not make herself more vulnerable\r\n \r\nTortured, tormented and\r\nraw she has to face the pain alone\r\nCould there be someone who really knows?\r\nThe hell she goes through when she take\r\nThe blade between her fingers\r\nThrough teary eyes see the blood begin to flow'),
(7, '2009-07-06 21:01:45', '1246906905', 1, 7, 'You Can Do', 'You can do with a lot\r\nOr you can do with what you''ve got\r\nAnd be alright, oh yeah\r\nMore than alright, oh yeah\r\n \r\nYou can take the ride out to somewhere\r\nOr the countryside\r\nEnjoy the view from the train\r\nOr the scenery from the highway\r\n \r\nDrink a cup of tea\r\nClimb a tree\r\nSit with a friend dreaming\r\n \r\nRow a river between mountains green\r\nOr walk a shore you''ve never seen\r\n \r\nPaint a picture\r\nWrite a song\r\nSleep in a forest as you move along\r\nOpportunity knocks at the door\r\nThere''s so much worth living for\r\nBuy a stupid souvenir\r\nTo remind me that I was there\r\nEmbrace the moment every day\r\nYou never know that will come your way\r\n \r\nYou can do with a lot\r\nOr you can do with what you''ve got\r\nAnd be alright, oh yeah\r\nMore than alright, oh yeah\r\n \r\nBecause you can be happy\r\nYou can be satisfied\r\nYou can lack nothing\r\nBe content with everything you have'),
(8, '2009-07-06 21:01:52', '1246906912', 1, 8, 'Where Are You?', 'I could trace the starlight pattern\r\nFollow you where ever you may lead\r\nI could dream of writing you a letter\r\nA thousand words could never say what I mean\r\n \r\nI could run the desert cross the ocean\r\nJust to hear you say my name\r\nI could meet you in the unexpected\r\nStay there indefinitely\r\n \r\nWhere are you?\r\nI need you\r\nI long for you\r\nSo much\r\n \r\nWhere are you?\r\nI miss you\r\nI long for you\r\nAnd your touch\r\n \r\nWish I could be where you are\r\nWhere are you?\r\nI love you in the silence of distance\r\nThough missing you is lemon juice on a paper cut\r\nBut there is some comfort in knowing\r\nYou''re my Band-Aid in a broken world\r\n \r\nHave we passed by one another?\r\nA million times unkowingly\r\nThe compass of the heart points to what we\r\nWant to find the most\r\n \r\nRepeat chorus\r\n \r\nSo near\r\nSo deep, high and wide\r\nSo close, yet so far\r\n \r\nWish I could be where you are\r\nWhere are you?'),
(9, '2009-07-06 21:02:00', '1246906920', 1, 9, 'See The Light', 'I want to see the light again\r\nAnd know that it is true\r\n \r\nA revelation from above\r\nA shaft of light shining with love\r\nWith angels singing hallelujah\r\nA light bulb goes on somehow\r\nAnd idea is growing now\r\nThe answers slowly becoming clear\r\n \r\nRepeat chorus\r\n \r\nWhy do we get stuck in our way of thinking?\r\nBlinded and fooled by our own ways\r\nOh, I want to be enlightened\r\nTo consider what I never did before\r\n \r\nRepeat chorus\r\n \r\nI wanna see the light\r\nI wanna see the light again\r\nShine the light on this subject\r\nMake it crystal clear\r\nI am not gonna turn a deaf ear\r\nI want to hear\r\n \r\nSo show\r\nCome on\r\nThe light\r\n \r\nRepeat chorus'),
(10, '2009-07-06 21:02:08', '1246906928', 1, 10, 'Without You', 'Like a rose\r\nThat has shed its petals\r\nLike a candle\r\nThat has lost its flame\r\nLike a playground\r\nWithout any kids around\r\nSo am I without you\r\n \r\nLike trying to write\r\nWith an empty pen\r\nLike a song\r\nWithout beginnning or a end\r\nLike a bridge\r\nBroken in two\r\nSo am I without you\r\n \r\nLike a phone that won''t ring\r\nLike a watch when you can''t see a thing\r\nLike checkmate on a black square\r\nSo am I if you''re not there\r\nHow can I begin to express the way I feel?\r\nWhen trying to make sense\r\nof things that seems so surreal\r\nToo many questions wasting too much time\r\nWhile you could be mine\r\n \r\nLike a shoe\r\nWithout a foot\r\nLike a smile\r\nWihtout one good tooth\r\nLike a knife\r\nThat has lost its fork as friend\r\nSo am I without you\r\nAnd so is life without you'),
(11, '2009-07-06 21:02:14', '1246906934', 1, 11, 'Searching', 'All of my life you were there\r\nAll of my life patiently waiting, waiting\r\nFor me to finally learn to trust the truth\r\n \r\nThe way you speak to me\r\nMake me feel like I am connected in every way\r\nThe way you hold me\r\nMake me sure that I will never let you go\r\n \r\nIt amazes me how you could\r\nhave loved me all this time\r\nLoved me the same\r\n \r\nAll of my life I''ve been searching\r\nAll of my life you were there\r\nAll of my life patiently waiting, waiting\r\nFor me to finally learn to trust the truth\r\n \r\nThe way you speak to me\r\nMake me feel like I am connected in every way\r\nThe way you hold me\r\nMake me sure that I will never let you go\r\nIt amazes me how you could\r\nhave loved me all this time\r\nLoved me the same\r\n \r\nRepeat chorus\r\n \r\nWaiting for destiny to be revealed\r\nRevelation without self regard\r\nRegard for nothing\r\nNothing to hinder or keep\r\nKeep walking in the way\r\nWay too hard\r\nHard to find the right direction\r\nDirected into destiny\r\nDestiny reveal yourself'),
(12, '2009-07-06 21:02:23', '1246906943', 1, 12, 'Just To Be With You', 'I will cross the broadest stream\r\nI will swim the deepest ocean\r\nJust to be with you\r\n \r\nI will sing you a love song\r\nThat will be forever more\r\nA love that will outlast a lifetime\r\nA dance upon the sea shore\r\n \r\nI will give it all up\r\nAnd sacrifice it all\r\nI will sell my soul or being\r\nJust to be with you\r\n \r\nThroughout life and all it''s seasons\r\nWhether good or bad\r\nThrough the joy, tears and sadness\r\nI want to cleave to you\r\nWhen I am cold and all alone\r\nWhen I am sick or afraid\r\nWhen my strength fails me\r\nI want you to be there for me\r\n \r\nI know prayer is a kind request\r\nRather than a harsh demand\r\nSo here I am praying pleading\r\nJust to be with you\r\n \r\nWhat do wish for?\r\nWhat do I dream of?\r\nWhat do I hope in?\r\nIf not in you\r\n \r\nSo I''ll sell my soul or being\r\nJust to be with you');
