<h1>Update Poem</h1>

<p>The picture will be resized to a width of 200 if it is wider.
<br />Upload of picture is not required. If none, the current picture (if any) will be kept.</p>

<?= $this->form ?>


<br class="clearBoth" />

<?php if (strlen($this->poem->picture) > 0) : ?>
	<img class="imgLeft" src="<?= $this->baseUrl() . '/uploads/poems/' . $this->poem->picture ?>" />
<?php else : ?>
	<p>No picture</p>
<?php endif ?>

