<h1><?= $this->title ?></h1>

<ul class="gallery">
<li><img src="<?= $this->baseUrl() . '/img/FoTgallery/booklet_front.jpg'; ?>" alt="Flight of Time cover"></li>
<li><img src="<?= $this->baseUrl() . '/img/FoTgallery/booklet_back.jpg'; ?>" alt="Flight of Time inside cover"></li>
<li><img src="<?= $this->baseUrl() . '/img/FoTgallery/cd.jpg'; ?>" alt="CD cover"></li>  
<li><img src="<?= $this->baseUrl() . '/img/FoTgallery/S1.jpg'; ?>" alt="So Sorry"></li>
<li><img src="<?= $this->baseUrl() . '/img/FoTgallery/S2.jpg'; ?>" alt="Smile"></li>
<li><img src="<?= $this->baseUrl() . '/img/FoTgallery/S3.jpg'; ?>" alt="Slow Down"></li>
<li><img src="<?= $this->baseUrl() . '/img/FoTgallery/S4.jpg'; ?>" alt="Resignation (giving up)"></li>
<li><img src="<?= $this->baseUrl() . '/img/FoTgallery/S5.jpg'; ?>" alt="Through"></li>
<li><img src="<?= $this->baseUrl() . '/img/FoTgallery/S6.jpg'; ?>" alt="Badly Misunderstood"></li>
<li><img src="<?= $this->baseUrl() . '/img/FoTgallery/S7.jpg'; ?>" alt="You Can Do"></li>
<li><img src="<?= $this->baseUrl() . '/img/FoTgallery/S8.jpg'; ?>" alt="Where Are You?"></li>
<li><img src="<?= $this->baseUrl() . '/img/FoTgallery/S9.jpg'; ?>" alt="See The Light"></li>
<li><img src="<?= $this->baseUrl() . '/img/FoTgallery/S10.jpg'; ?>" alt="Without You"></li>
<li><img src="<?= $this->baseUrl() . '/img/FoTgallery/S11.jpg'; ?>" alt="Searching"></li>
<li><img src="<?= $this->baseUrl() . '/img/FoTgallery/S12.jpg'; ?>" alt="Just To Be With You"></li>
<li><img src="<?= $this->baseUrl() . '/img/FoTgallery/credits.jpg'; ?>" alt="Credits"></li>
<li><img src="<?= $this->baseUrl() . '/img/FoTgallery/cd_behind.jpg'; ?>" alt="Flight of Time"></li>
</ul>
<p class="clearBoth"></p>
<p class="mainText">&nbsp;</p>
<p class="mainImg"><img src="<?= $this->baseUrl() . '/img/FoTgallery/logoback.png'; ?>" width="500" height="500" alt=""></p>

<p class="mainCredits"><a href="http://www.edgephotographic.com" target="_blank"><img src="<?= $this->baseUrl() . '/img/FoTgallery/edge_photographic.png'; ?>" alt="Edge Photographic"></a></p>
